language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"

sudo: false

matrix:
  fast_finish: true

install:
  - pip install tox-travis
  - pip install codecov

script:
  - tox

after_success:
  - codecov
